language: python
python:
  - "3.4"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - curl -L  https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz -o etcd-v0.4.6-linux-amd64.tar.gz
  - tar xzvf etcd-v0.4.6-linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/etcd-v0.4.6-linux-amd64
script: make vtest

